{
 "title": "BU usage (WIP) from Rob",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Cluster Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace) "
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_info{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(kafka_topic_partitions{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\", namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{ container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{ container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Max Kafka clusters",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(strimzi_resources{kind=~\"Kafka\"}[24h] offset 24h)",
     "legendFormat": "48h to 24h ago"
    },
    {
     "expr": "max_over_time(strimzi_resources{kind=~\"Kafka\"}[24h])",
     "legendFormat": "last 24h"
    },
    {
     "expr": "max_over_time(strimzi_resources{kind=~\"Kafka\"}[24h]) + max_over_time(strimzi_resources{kind=~\"Kafka\"}[24h] offset 24h)",
     "legendFormat": "last 48h"
    }
   ]
  },
  {
   "title": "Current Openshift Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cluster_version{type=\"completed\"}) by (version,cluster_id) * on (cluster_id) group_left () count(subscription_sync_total{installed=~\"^strimzi.*$\"}) by (cluster_id)"
    }
   ]
  },
  {
   "title": "Openshift Clusters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(cluster_version{type=\"completed\"}) by (version,cluster_id) * on (cluster_id) group_left () count(subscription_sync_total{installed=~\"^strimzi.*$\"}) by (cluster_id)",
     "legendFormat": "clusters"
    }
   ]
  },
  {
   "title": "Total input Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messages_in_total)"
    }
   ]
  },
  {
   "title": "Input Messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messages_in_total)",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Total input bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytes_in_total)"
    }
   ]
  },
  {
   "title": "Input throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytes_in_total[1m])*60)",
     "legendFormat": "data"
    }
   ]
  },
  {
   "title": "Current Kafka Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Kafka Clusters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})",
     "legendFormat": "clusters"
    }
   ]
  },
  {
   "title": "Total output bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytes_out_total)"
    }
   ]
  },
  {
   "title": "Ouput throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytes_out_total[1m])*60)",
     "legendFormat": "data"
    }
   ]
  }
 ]
}