{
 "title": "MK - Usage",
 "description": "Overview of Openshift and Kafka cluster for the Business Unit",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Component Counts and Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Kafka Cluster Usage",
   "type": "table",
   "description": "The number of Kafka components per a Kafka cluster and network traffic over the past 24 hours",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions) by (namespace)"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_info{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(kafka_topic_partitions{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\", namespace !~ \".*minio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}[$__range])) by (namespace)"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}[$__range])) by (namespace)"
    }
   ]
  },
  {
   "title": "Network Transmit Throughput (Bytes) [top 10]",
   "type": "graph",
   "description": "Network throughput in bytes for each Kafka cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(increase(container_network_transmit_bytes_total{container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}[$__range])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Receive Throughput (Bytes) [top10]",
   "type": "graph",
   "description": "Network throughput  received in bytes for each Kafka cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(container_network_receive_bytes_total{container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\",namespace !~\".*obser.*\",namespace !~ \".*logging.*\",namespace !~ \".*minio.*\"}[$__range])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Openshift Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Openshift Clusters",
   "type": "stat",
   "description": "The current number of Openshift clusters ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(count(cluster_version{type=\"completed\"}) by (version, cluster_id) * on (cluster_id) group_left () strimzi_resources{kind=~\"Kafka\"}) by (cluster_id))"
    }
   ]
  },
  {
   "title": "Openshift Cluster Count",
   "type": "graph",
   "description": "The number of Kafka Openshift clusters over the selected time period",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count(count(cluster_version{type=\"completed\"}) by (version, cluster_id) * on (cluster_id) group_left () strimzi_resources{kind=~\"Kafka\"}) by (cluster_id))"
    }
   ]
  },
  {
   "title": "Kakfa Instances Per Openshift Cluster",
   "type": "table",
   "description": "The number of Kafka instances currently on each Openshift Cluster",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(cluster_version{type=\"completed\"}) by (version, cluster_id) * on (cluster_id) group_left () strimzi_resources{kind=~\"Kafka\"}"
    }
   ]
  },
  { "title": "Kafka Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Kafka Clusters",
   "type": "stat",
   "description": "The current number of Kafka clusters ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Kafka Cluster Count",
   "type": "graph",
   "description": "The number of Kafka clusters over the selected time period",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})",
     "legendFormat": "Clusters"
    }
   ]
  }
 ]
}