apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: observability-operator
  namespace: <NAMESPACE>
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: observability-operator
  source: observability-operator-manifests
  sourceNamespace: <NAMESPACE>
