"enablePasswordDB": true
"issuer": "http://dex.dex.svc.cluster.local:5556/dex"
"logger":
  "level": "debug"
"oauth2":
  "passwordConnector": "local"
"staticClients":
- "id": "tenant1"
  "name": "tenant1"
  "secret": "ZXhhbXBsZS1hcHAtc2VjcmV0"
- "id": "tenant2"
  "name": "tenant2"
  "secret": "dGVuYW50Mi1wYXNzCg=="
"staticPasswords":
- "email": "admin@example.com"
  "hash": "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  "userID": "08a8684b-db88-4b73-90a9-3cd1661f5466"
  "username": "admin"
"storage":
  "config":
    "file": "/storage/dex.db"
  "type": "sqlite3"
"web":
  "http": "0.0.0.0:5556"
"expiry":
  "deviceRequests": "8760h"
  "signingKeys": "8760h"
  "idTokens": "8760h"
